### ISSUE TITLE
Reason for lodash-min.

### ISSUE THREAD

**Issue by jdalton** [ide/ld-min#1]
Hi James!

I noticed lodash-min pop up and it's just a minified lodash. I'm wondering what the use case for it is.

**Comment by ide** [comment]
Hi @jdalton - I wanted a convenient way to load a minified build for performance reasons. It's a bit faster to read fewer bytes off of disk and to have to do less string copying behind the scenes, which were the main reasons.

Longer-term, my own build process should minify all my packages in node_modules (and do other optimizations like bundling them together, etc.), but this was the easiest way to get some of the perf improvements at the moment.

**Comment by jdalton** [comment]
Do you have any of that load data handy?

**Comment by ide** [comment]
I don't have the numbers (I last investigate a couple of months ago), sorry. I was measuring the execution time in mobile safari which is maybe why I was seeing a difference.

**Comment by jdalton** [comment]
With v3 you can cherry-pick modules from lodash like `require('lodash/array/chunk')` and then browserify/webpack + uglify to create smaller builds. For example see https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144.

My main concern is that `lodash-min` looks largely unnecessary and looks like a lodash project. If it turns out not to be needed would you be open to unpublishing?

**Comment by jdalton** [comment]
My main concern is that `lodash-min` looks largely unnecessary and looks like a lodash project. If it turns out not to be needed would you be open to unpublishing?

**Comment by ide** [comment]
I understand. Would you be OK with the package being renamed to something like "ld-min"?

**Comment by jdalton** [comment]
> Would you be OK with the package being renamed to something like "ld-min"?

Ya that would rock. Also let me know if the browserify/webpack+uglify and cherry-picking modules route works for you.

**Comment by ide** [comment]
Will do.
